- shell:
    - command: $(which sudo) apt-get update -y && $(which sudo) apt-get upgrade -y
      description: Updating and upgrading apt-get...
      stderr: true
    - command:
        $(which sudo) apt-get install -y --no-install-recommends sudo vim zsh curl wget apt-transport-https
        ca-certificates curl gnupg lsb-release
      description: Installing packages...
      stderr: true
    - command:
        $(which sudo) curl -fsSL https://download.docker.com/linux/debian/gpg | $(which sudo) gpg --dearmor -o
        /usr/share/keyrings/docker-archive-keyring.gpg
      description: Adding docker GPG key...
      stderr: true
    - command:
        $(which sudo) echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
        https://download.docker.com/linux/debian $(lsb_release -cs) stable" | $(which sudo) tee
        /etc/apt/sources.list.d/docker.list > /dev/null
      description: Settinging up docker repository...
      stderr: true
    - command: $(which sudo) apt-get update -y && $(which sudo) apt-get upgrade -y
      description: Updating and upgrading apt-get...
      stderr: true
    - command: $(which sudo) apt-get install -y --no-install-recommends docker-ce-cli
      description: Installing docker cli...
      stderr: true
    - command:
        $(which sudo) curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname
        -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      description: Install docker-compose cli
      stderr: true
    - command: $(which sudo) +x /usr/local/bin/docker-compose
      description: Set permissions for docker-compose
      stderr: true
