- shell:
    - export DEBIAN_FRONTEND=noninteractive
    - if command -v sudo; then export SUDO="sudo"; else export SUDO=""; fi
    - command: ${SUDO} apt-get update && ${SUDO} apt-get upgrade
      description: Updating and upgrading apt-get...
      stderr: true
    - command:
        ${SUDO} apt-get -y install --no-install-recommends ${SUDO} vim zsh curl wget apt-transport-https ca-certificates
        curl gnupg lsb-release
      description: Installing packages...
      stderr: true
    - command:
        ${SUDO} curl -fsSL https://download.docker.com/linux/debian/gpg | ${SUDO} gpg --dearmor -o
        /usr/share/keyrings/docker-archive-keyring.gpg
      description: Adding docker GPG key...
      stderr: true
    # - command:
    #     ${SUDO} echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
    #     https://download.docker.com/linux/debian $(lsb_release -cs) stable" | ${SUDO} tee
    #     /etc/apt/sources.list.d/docker.list > /dev/null
    #   description: Settinging up docker repository...
    #   stderr: true
    # - command: ${SUDO} apt-get update && ${SUDO} apt-get upgrade
    #   description: Updating and upgrading apt-get...
    #   stderr: true
    # - command: ${SUDO} apt-get install docker-ce-cli
    #   description: Installing docker cli...
    #   stderr: true
