- tap:
    - cask-drivers

- brew:
    - git
    - python
    - llvm
    - gcc
    - cmake
    - tree
    - parallel
    - ssh-copy-id

- cask:
    - visual-studio-code
    - miniconda
    - iterm2
    - google-chrome
    - google-backup-and-sync
    - firefox
    - shiftit
    - virtualbox
    - logitech-options
