- tap:
    - homebrew/cask-drivers
    - heroku/brew

- brew:
    - git
    - python
    - llvm
    - gcc
    - cmake
    - tree
    - parallel
    - ssh-copy-id
    - open-mpi
    - boost
    - coreutils
    - heroku

- cask:
    - visual-studio-code
    - miniconda
    - iterm2
    - google-chrome
    - google-backup-and-sync
    - firefox
    - shiftit
    - logitech-options
    - vagrant
    - docker
    # - virtualbox  # intalling this causes script to fail for MacOS >=10.13 because it is a kernel extension
