- tap:
    - homebrew/cask-drivers

- brew:
    - git
    - python
    - llvm
    - gcc
    - cmake
    - tree
    - parallel
    - ssh-copy-id

- cask:
    - visual-studio-code
    - miniconda
    - iterm2
    - google-chrome
    - google-backup-and-sync
    - firefox
    - shiftit
    - logitech-options
    # - virtualbox  # intalling this causes script to fail for MacOS >=10.13 because it is a kernel extension
