- tap:
    - homebrew/cask-drivers
    - heroku/brew

- brew:
    - git
    - python
    - llvm
    - gcc
    - cmake
    - clang-format
    - tree
    - parallel
    - ssh-copy-id
    - coreutils
    - heroku
    - node
    - typescript
    - nvm
    - yarn
    - terraform
    - act # local github actions runner
    - wget
    - mkcert
    - nss
    - helm
    - cookiecutter
    - aws
    - sops

- cask:
    - visual-studio-code
    - miniconda
    - iterm2
    - google-chrome
    - google-backup-and-sync
    - firefox
    - shiftit
    - logitech-options
    - vagrant
    - docker
    - arduino
    - spotify
    - vnc-viewer
    # - terraspace
    # - virtualbox  # intalling this causes script to fail for MacOS >=10.13 because it is a kernel extension
