- vscode:
    ms-python.python:
      status: install
      insiders: false
    ms-vscode.cpptools:
      status: install
      insiders: false
    file-icons.file-icons:
      status: install
      insiders: false
    njpwerner.autodocstring:
      status: install
      insiders: false
    fabiospampinato.vscode-highlight:
      status: install
      insiders: false
    redhat.vscode-yaml:
      status: install
      insiders: false
    twxs.cmake:
      status: install
      insiders: false
    ms-vscode.cmake-tools:
      status: install
      insiders: false

- link:
    ~/Library/Application\ Support/Code/User/keybindings.json:
      if: '["$OSTYPE" == "darwin"*]'
      force: true
      path: ~/.dotfiles/vscode/keybindings.json
    ~/Library/Application\ Support/Code/User/settings.json:
      if: '["$OSTYPE" == "darwin"*]'
      force: true
      path: ~/.dotfiles/vscode/settings.json
    ~/.vscode/extensions/ericdang.custom-themes:
      path: ~/.dotfiles/vscode/custom-themes
