- vscode:
    njpwerner.autodocstring:
      status: install
      insiders: false
    coenraads.bracket-pair-colorizer-2:
      status: install
      insiders: false
    xaver.clang-format:
      status: install
      insiders: false
    twxs.cmake:
      status: install
      insiders: false
    ms-vscode.cmake-tools:
      status: install
      insiders: false
    ms-vscode.cpptools:
      status: install
      insiders: false
    file-icons.file-icons:
      status: install
      insiders: false
    eamodio.gitlens:
      status: install
      insiders: false
    mhutchie.git-graph:
      status: install
      insiders: false
    yzhang.markdown-all-in-one:
      status: install
      insiders: false
    esbenp.prettier-vscode:
      status: install
      insiders: false
    ms-python.python:
      status: install
      insiders: false
    ms-vscode-remote.remote-containers:
      status: install
      insiders: false
    ms-azuretools.vscode-docker:
      status: install
      insiders: false
    batisteo.vscode-django:
      status: install
      insiders: false
    dbaeumer.vscode-eslint:
      status: install
      insiders: false
    mkxml.vscode-filesize:
      status: install
      insiders: false
    ms-python.vscode-pylance:
      status: install
      insiders: false

- link:
    ~/Library/Application Support/Code/User/keybindings.json:
      if: echo ${OSTYPE} | grep "darwin"
      force: true
      path: ~/.dotfiles/vscode/keybindings.json
    ~/Library/Application Support/Code/User/settings.json:
      if: echo ${OSTYPE} | grep "darwin"
      force: true
      path: ~/.dotfiles/vscode/settings.json
    ~/.vscode/extensions/ericdang.custom-themes:
      path: ~/.dotfiles/vscode/custom-themes
