- defaults:
    link:
      create: true
      relink: true

- clean: ["~"]

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ""
    ~/.gitconfig:
    ~/.gitignore:
    ~/.inputrc:
    ~/.shell:
    ~/.zshrc:

- brew:
    - tree
    # - parallel
    # - ssh-copy-id
    # - cmake

- cask:
    - visual-studio-code
    # - virtualbox

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - command: ./macos.sh
      stdin: true
      stdout: true
