- defaults:
    link:
      create: true
      relink: true

- clean: ["~"]

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ""
    ~/.gitconfig:
    ~/.gitignore:
    ~/.inputrc:
    ~/.shell:
    ~/.zshrc:

- shell:
    - git submodule sync --recursive
    # the following have to run after linking ~/.gitconfig
    - git update-submodules
    - ./macos.sh
