- defaults:
    link:
      create: true
      relink: true

- clean: ["~"]

- link:
    ~/.bash:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.dotfiles: ""
    ~/.gitconfig:
    ~/.gitignore:
    ~/.inputrc:
    ~/.shell:
    ~/.zshrc:
    ~/.config/.pylintrc:
    ~/.config/.condarc:
    ~/.config/.clang-format:

- brew:
    - tree
    # - parallel
    # - ssh-copy-id
    # - cmake

- cask:
    - visual-studio-code
    # - virtualbox

- vscode:
    ms-python.python:
      status: install
    ms-vscode.cpptools:
      status: install
    file-icons.file-icons:
      status: install
    njpwerner.autodocstring:
      status: install
    fabiospampinato.vscode-highlight:
      status: install
    redhat.vscode-yaml:
      status: install
    twxs.cmake:
      status: install
    ms-vscode.cmake-tools:
      status: install

- shell:
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - ./macos.sh
