language: shell
jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11.6
    - os: osx
      osx_image: xcode12.2

sudo: true
paranoid_mode: false

before_script:
  - mkdir -p ~/dotfiles-install-dir

script:
  - HOME=~/dotfiles-install-dir
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sed -i '' '/virtualbox/d' ./meta/configs/brew.yaml; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sed -i '' '/- shell:/d' ./meta/configs/zsh.yaml; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sed -i '' '/chsh/d' ./meta/configs/zsh.yaml; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sed -i '/- shell:/d' ./meta/configs/zsh.yaml; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sed -i '/chsh/d' ./meta/configs/zsh.yaml; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then travis_wait 30 ./install-profile macos; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then travis_wait 30 ./install-profile docker-linux; fi
