language: shell
jobs:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode11

sudo: true
paranoid_mode: false

before_script:
  - mkdir -p ~/dotfiles-install-dir

script:
  - HOME=~/dotfiles-install-dir
  - sed -i '' '/virtualbox/d' ./meta/configs/brew.yaml
  - sed -i '' '/- shell:/d' ./meta/configs/zsh.yaml
  - sed -i '' '/chsh/d' ./meta/configs/zsh.yaml
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ./install-profile macos
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then ./install-profile linux
