language: shell
os: osx
osx_image: xcode11

sudo: true
paranoid_mode: false

before_script:
  - mkdir -p ~/dotfiles-install-dir

script:
  - HOME=~/dotfiles-install-dir
  - sed -i '' '/virtualbox/d' ./meta/configs/brew.yaml
  - sed -i '' '/- shell:/d' ./meta/configs/zsh.yaml
  - sed -i '' '/chsh/d' ./meta/configs/zsh.yaml
  - ./install-profile macos
