language: shell
os: osx
osx_image: xcode11

sudo: true
paranoid_mode: false

before_script:
  - mkdir -p ~/dotfiles-install-dir

script:
  - HOME=~/dotfiles-install-dir && 'brew() { if [[ $@ == *"virtualbox"* || $@ == *"llvm"* || $@ == *"gcc"* ]]; then return 0; else command "$@"; fi; }' && ./install-profile macos
