language: python
os: osx
osx_image: xcode11
python:
  - "3.7"
  # - "2.7"
  # - "pypy"
  # - "3.4"
  # - "3.5"
  # - "3.6"
  # - "nightly"

sudo: false

before_script:
  - mkdir -p ~/dotfiles-install-dir
  - ls -la
  - pwd

script:
  - HOME=~/dotfiles-install-dir ./install
