#!/usr/bin/env bash

# Taken from https://github.com/anishathalye/dotbot/wiki/Tips-and-Tricks

set -e

BASE_CONFIG="base"
CONFIG_SUFFIX=".yaml"

META_DIR="meta"
CONFIG_DIR="configs"
PROFILES_DIR="profiles"

DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive --remote

for config in ${@}; do
	configFile="$(mktemp)" ; echo -e "$(<"${BASEDIR}/${META_DIR}/${BASE_CONFIG}${CONFIG_SUFFIX}")\n$(<"${BASEDIR}/${META_DIR}/${CONFIG_DIR}/${config}${CONFIG_SUFFIX}")" > "$configFile"
	"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "$configFile" --plugin-dir dotbot-brew --plugin-dir dotbot-vscode; rm -f "$configFile"
done