name: Test

on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  test-macos:
    strategy:
      matrix:
        os: [macos-14, macos-15]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Write template configs
        run: |
          mkdir -p ~/.config/chezmoi && \
          cat << EOT >> ~/.config/chezmoi/chezmoi.toml
          [data]
              name = "Test User"
              email = "testuser@demo.com"
              profile = "root-osx"
              hostname = "test-ci"
          EOT

      - name: Remove preexisting binaries
        run: |
          rm -f /opt/homebrew/bin/aws || true
          rm -f /opt/homebrew/bin/aws_completer || true
          rm -f /opt/homebrew/bin/conda || true

      - name: Install configurations
        run: sh -c "$(curl -fsLS https://chezmoi.io/get)" -- init --apply https://github.com/e-dang/dotfiles

      - name: Test installation
        run: |
          brew list
